### PR TITLE
Allow incremental addition of match list entries

### PR DESCRIPTION
**Pull request by Devirex**
* **Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added / modified (needed for for bug fixes / features)
- [x] commandref has been added / updated (needed for bug fixes / features)
- [ ] CHANGED has been updated (needed for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature to add MatchList-entries

* **What is the current behavior?** (You can also link to an open issue here)
Override complete MatchList

* **What is the new behavior (if this is a feature change)?**
Entries from myMatchList attribute will be added to default MatchList

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Comment by sidey79** [comment]
Thanks you dir that Pull Requests.

There is already a Attribut called

MatchList

There is not very much difference in the behaviour. Die you think we can reuse this and only change the evaluation ?

**Comment by sidey79** [comment]
Looks good.
I`ll check how we can extend automated tests.

**Comment by sidey79** [comment]
@Devirex 

Just a reminder for my last question

**Comment by Devirex** [comment]
> @Devirex
> 
> Just a reminder for my last question

Hi,

sorry was on Holiday the last three weeks. I’ll have a look at this, this week

**Comment by Devirex** [comment]
Hi, 

had a look in this today, I don't understand where you find "CommandDeleteAttr". 
The "MatchList" Attribute was always be there and if there is no valid hash List which is set then it will default to standard.

**Comment by sidey79** [comment]
> Hi,
> 
> had a look in this today, I don't understand where you find "CommandDeleteAttr". The "MatchList" Attribute was always be there and if there is no valid hash List which is set then it will default to standard.

CommandDeleteAttr is a perl command and it already does the job of deleting a attribute so ther is no need, that we do it.
https://github.com/fhem/fhem-mirror/blob/19f4992fb1cb47ee91e0f856de85ea12e23dfeb3/fhem/fhem.pl#L2380

**Pull request merged**
