### PR TITLE
00_SIGNALduino.pm - log output

### PR DESCRIPTION
**Pull request by HomeAutoUser**
- Adaptation of texts + log output only if output parameters available

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
better overview in the log output

* **What is the current behavior?** (You can also link to an open issue here)
Ein "Durcheinader der Formulierungen" ;-)

* **What is the new behavior (if this is a feature change)?**
Eine einheitliche Ausgabe und Schönheitskorrektur ;-)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by sidey79** [comment]
Danke für die Anpassung. Hast Du ein Beispiel der Logausgabe parat?

**Comment by HomeAutoUser** [comment]
Hallo @sidey79,

nun sieht es so aus:
>2018.07.02 18:49:35 0: Server started with 291 defined entities (fhem.pl:16866/2018-06-14 perl:5.024001 os:linux user:fhem pid:32422)
2018.07.02 18:49:35 3: radino_433Mhz: ID blacklist=6,20,31,40,52,63
2018.07.02 18:49:35 3: radino_433Mhz: IDlist development=80y,81y
2018.07.02 18:49:35 3: radino_433Mhz: ID=p76 skiped (developId=p)
2018.07.02 18:49:35 3: radino_433Mhz: ID=p76.1 skiped (developId=p)
2018.07.02 18:49:35 3: radino_433Mhz: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 65 68 7 72.1
2018.07.02 18:49:35 3: radino_433Mhz: IDlist MU 13.1 16 21 24 26 27 28 29 30 36 37 39 44 44.1 45 46 48 49 5 50 56 59 60 61 62 64 66 67 69 70 71 72 73 74 75 77 78 79 8 9
2018.07.02 18:49:35 3: radino_433Mhz: IDlist MC 10 11 12 18 43 47 57 58
2018.07.02 18:49:35 3: nano_433Mhz: ID blacklist=6,20,31,40,52,63
2018.07.02 18:49:35 3: nano_433Mhz: ID=77 skiped (developId=y)
2018.07.02 18:49:35 3: nano_433Mhz: ID=73 skiped (developId=y)
2018.07.02 18:49:35 3: nano_433Mhz: ID=p76 skiped (developId=p)
2018.07.02 18:49:35 3: nano_433Mhz: ID=p76.1 skiped (developId=p)
2018.07.02 18:49:35 3: nano_433Mhz: ID=74 skiped (developId=y)
2018.07.02 18:49:35 3: nano_433Mhz: ID=78 skiped (developId=y)
2018.07.02 18:49:35 3: nano_433Mhz: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 65 68 7 72.1
2018.07.02 18:49:35 3: nano_433Mhz: IDlist MU 13.1 16 21 24 26 27 28 29 30 36 37 39 44 44.1 45 46 48 49 5 50 56 59 60 61 62 64 66 67 69 70 71 72 75 79 8 9
2018.07.02 18:49:35 3: nano_433Mhz: IDlist MC 10 11 12 18 43 47 57 58
2018.07.02 18:49:35 3: nano_868Mhz: ID whitelist=3,12,60,70,73,73.1,74
2018.07.02 18:49:35 3: nano_868Mhz: ID blacklist=6,20,40
2018.07.02 18:49:35 3: nano_868Mhz: IDlist development=73y,73.1y,73.2y,74y
2018.07.02 18:49:35 3: nano_868Mhz: IDlist MS 3
2018.07.02 18:49:35 3: nano_868Mhz: IDlist MU 60 70 73 74
2018.07.02 18:49:35 3: nano_868Mhz: IDlist MC 12
2018.07.02 18:49:35 3: xduino: IDlist development=73y,73.1y,74y
2018.07.02 18:49:35 3: xduino: ID=p76 skiped (developId=p)
2018.07.02 18:49:35 3: xduino: ID=p76.1 skiped (developId=p)
2018.07.02 18:49:35 3: xduino: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 6 65 68 7 72.1
2018.07.02 18:49:35 3: xduino: IDlist MU 13.1 16 20 21 24 26 27 28 29 30 31 36 37 39 40 44 44.1 45 46 48 49 5 50 56 59 60 61 62 63 64 66 67 69 70 71 72 73 74 75 77 78 79 8 9
2018.07.02 18:49:35 3: xduino: IDlist MC 10 11 12 18 43 47 52 57 58
2018.07.02 18:49:35 3: signalESP: ID blacklist=6,7,20,40,52,57
2018.07.02 18:49:35 3: signalESP: ID=77 skiped (developId=y)
2018.07.02 18:49:35 3: signalESP: ID=73 skiped (developId=y)
2018.07.02 18:49:35 3: signalESP: ID=p76 skiped (developId=p)
2018.07.02 18:49:35 3: signalESP: ID=63 skiped (developId=y)
2018.07.02 18:49:35 3: signalESP: ID=p76.1 skiped (developId=p)
2018.07.02 18:49:35 3: signalESP: ID=74 skiped (developId=y)
2018.07.02 18:49:35 3: signalESP: ID=78 skiped (developId=y)
2018.07.02 18:49:35 3: signalESP: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 65 68 72.1
2018.07.02 18:49:35 3: signalESP: IDlist MU 13.1 16 21 24 26 27 28 29 30 31 36 37 39 44 44.1 45 46 48 49 5 50 56 59 60 61 62 64 66 67 69 70 71 72 75 79 8 9
2018.07.02 18:49:35 3: signalESP: IDlist MC 10 11 12 18 43 47 58
2018.07.02 18:49:35 3: radino_433Mhz/init: disable receiver (XQ)

**VOR der ÄNDERUNG:**

>2018.07.02 17:43:02 3: radino_433Mhz sduinoIdList: whitelistIds=
2018.07.02 17:43:02 3: radino_433Mhz sduinoIdList: blacklistIds=6,20,31,40,52,63
2018.07.02 17:43:02 3: radino_433Mhz sduinoIdList: development=80y,81y
2018.07.02 17:43:02 3: radino_433Mhz: ID=p76 skiped (developId=p)
2018.07.02 17:43:02 3: radino_433Mhz: ID=p76.1 skiped (developId=p)
2018.07.02 17:43:02 3: radino_433Mhz: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 65 68 7 72.1
2018.07.02 17:43:02 3: radino_433Mhz: IDlist MU 13.1 16 21 24 26 27 28 29 30 36 37 39 44 44.1 45 46 48 49 5 50 56 59 60 61 62 64 66 67 69 70 71 72 73 74 75 77 78 79 8 80 81 9
2018.07.02 17:43:02 3: radino_433Mhz: IDlist MC 10 11 12 18 43 47 57 58
2018.07.02 17:43:02 3: nano_433Mhz sduinoIdList: whitelistIds=
2018.07.02 17:43:02 3: nano_433Mhz sduinoIdList: blacklistIds=6,20,31,40,52,63
2018.07.02 17:43:02 3: nano_433Mhz sduinoIdList: development=80y,81y
2018.07.02 17:43:02 3: nano_433Mhz: ID=p76 skiped (developId=p)
2018.07.02 17:43:02 3: nano_433Mhz: ID=p76.1 skiped (developId=p)
2018.07.02 17:43:02 3: nano_433Mhz: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 65 68 7 72.1
2018.07.02 17:43:02 3: nano_433Mhz: IDlist MU 13.1 16 21 24 26 27 28 29 30 36 37 39 44 44.1 45 46 48 49 5 50 56 59 60 61 62 64 66 67 69 70 71 72 73 74 75 77 78 79 8 80 81 9
2018.07.02 17:43:02 3: nano_433Mhz: IDlist MC 10 11 12 18 43 47 57 58
2018.07.02 17:43:02 3: nano_868Mhz sduinoIdList: whitelistIds=3,12,60,70,73,73.1,74
2018.07.02 17:43:02 3: nano_868Mhz sduinoIdList: blacklistIds=6,20,40
2018.07.02 17:43:02 3: nano_868Mhz sduinoIdList: development=73y,73.1y,73.2y,74y,81y
2018.07.02 17:43:02 3: nano_868Mhz: IDlist MS 3
2018.07.02 17:43:02 3: nano_868Mhz: IDlist MU 60 70 73 74
2018.07.02 17:43:02 3: nano_868Mhz: IDlist MC 12
2018.07.02 17:43:02 3: xduino sduinoIdList: whitelistIds=
2018.07.02 17:43:02 3: xduino sduinoIdList: blacklistIds=
2018.07.02 17:43:02 3: xduino sduinoIdList: development=73y,73.1y,74y
2018.07.02 17:43:02 3: xduino: ID=p76 skiped (developId=p)
2018.07.02 17:43:02 3: xduino: ID=p76.1 skiped (developId=p)
2018.07.02 17:43:02 3: xduino: IDlist MS 0 1 13 13.2 14 15 17 2 22 23 25 3 3.1 32 33 35 38 4 41 51 55 6 65 68 7 72.1
2018.07.02 17:43:02 3: xduino: IDlist MU 13.1 16 20 21 24 26 27 28 29 30 31 36 37 39 40 44 44.1 45 46 48 49 5 50 56 59 60 61 62 63 64 66 67 69 70 71 72 73 74 75 77 78 79 8 80 81 9
2018.07.02 17:43:02 3: xduino: IDlist MC 10 11 12 18 43 47 52 57 58
2018.07.02 17:43:02 3: signalESP sduinoIdList: whitelistIds=
2018.07.02 17:43:02 3: signalESP sduinoIdList: blacklistIds=6,7,20,40,52,57
2018.07.02 17:43:02 3: signalESP sduinoIdList: development=
2018.07.02 17:43:02 3: signalESP: ID=78 skiped (developId=y)
2018.07.02 17:43:02 3: signalESP: ID=77 skiped (developId=y)
2018.07.02 17:43:02 3: signalESP: ID=74 skiped (developId=y)
2018.07.02 17:43:02 3: signalESP: ID=63 skiped (developId=y)
2018.07.02 17:43:02 3: signalESP: ID=p76 skiped (developId=p)
2018.07.02 17:43:02 3: signalESP: ID=73 skiped (developId=y)

**Comment by sidey79** [comment]
@Ralf9 
passt für micht, für dich auch okay?

**Comment by Ralf9** [comment]
> 2018.07.02 18:49:35 3: radino_433Mhz: ID blacklist=6,20,31,40,52,63
> 2018.07.02 18:49:35 3: radino_433Mhz: IDlist development=80y,81y
> 2018.07.02 18:49:35 3: radino_433Mhz: ID=p76 skiped (developId=p)
> 2018.07.02 18:49:35 3: radino_433Mhz: ID=p76.1 skiped (developId=p)
> 2018.07.02 18:49:35 3: nano_868Mhz: ID whitelist=3,12,60,70,73,73.1,74

Konsequent wäre es das "IDlist" überall einzufügen:
```
 2018.07.02 18:49:35 3: radino_433Mhz IDlist: blacklist=6,20,31,40,52,63
 2018.07.02 18:49:35 3: radino_433Mhz IDlist: development=80y,81y
 2018.07.02 18:49:35 3: radino_433Mhz IDlist: ID=p76 skiped (developId=p)
 2018.07.02 18:49:35 3: radino_433Mhz IDlist: ID=p76.1 skiped (developId=p)
 2018.07.02 18:49:35 3: nano_868Mhz IDlist: whitelist=3,12,60,70,73,73.1,74
```

Aufgrund des #242 "function developId incorrect ?" habe ich mir die developId Behandlung nochmal angeschaut und einige Anpassungen vorgenommen

**Comment by HomeAutoUser** [comment]
Hallo @sidey79 + @Ralf9 ,

>Konsequent wäre es das "IDlist" überall einzufügen:

Du hast Recht. Ich habe dies auch schon gedacht als ich das mir angesehen hatte gestern aber mich störte die doppelte List Bennenung Bsp: " IDlist: blacklist" Wie wäre es mit dieser Variante??

```
2018.07.02 18:49:35 3: radino_433Mhz IDlist: black=6,20,31,40,52,63
2018.07.02 18:49:35 3: radino_433Mhz IDlist: development=80y,81y
2018.07.02 18:49:35 3: radino_433Mhz IDlist: ID=p76 skiped (developId=p)
2018.07.02 18:49:35 3: radino_433Mhz IDlist: ID=p76.1 skiped (developId=p)
2018.07.02 18:49:35 3: radino_433Mhz IDlist: white=3,12,60,70,73,73.1,74
```

Würde den PR vornehmen bei Abnickung.

>Aufgrund des #242 "function developId incorrect ?" habe ich mir die developId Behandlung nochmal angeschaut und einige Anpassungen vorgenommen

Kannst du bitte einen PR machen @Ralf9 ?

**Comment by Ralf9** [comment]
> Du hast Recht. Ich habe dies auch schon gedacht als ich das mir angesehen hatte gestern aber mich störte die doppelte List Bennenung Bsp: " IDlist: blacklist" Wie wäre es mit dieser Variante??

Wenn es für Sidey so auch ok ist.

>> Aufgrund des #242 "function developId incorrect ?" habe ich mir die developId Behandlung >> nochmal angeschaut und einige Anpassungen vorgenommen

> Kannst du bitte einen PR machen @Ralf9 ?

Da es dann zwei PR parallel geben würde, ist es wahrscheinlich besser wenn Du dies
https://github.com/RFD-FHEM/RFFHEM/issues/242#issuecomment-398514077
bei Dir reinkopierst und dann ein PR machst

**Comment by sidey79** [comment]
Der PR sollte durchaus so bleiben.

Am Ende erweitert er den PR #245 aber so bekommen wir einen guten Überblick.

Aus meiner Sicht ist es auch in Ordnung. Wichtig ist mir, dass die Logmeldungen und Docs konsistent sind.
Das scheint mir hier der Fall und das Sortieren ist auch eine gute Idee.

**Comment by sidey79** [comment]
#15b41bb merges this

**Comment by HomeAutoUser** [comment]
@sidey79,
vielen Dank für das mergen.

Ich hätte noch den Vorschlag, das
>2018.07.04 00:02:46 3: signalESP: IDlist skiped (developID=p) p76 p76.1
2018.07.04 00:02:46 3: signalESP: IDlist skiped (developID=y) y63 y73 y74 y77 y78

zusammen in eine Liste macht.
>2018.07.04 00:02:46 3: signalESP: IDlist skiped (developID) p76 p76.1 y63 y73 y74 y77 y78

Was hälst du davon ?
Den Code habe ich schon vorbereitet.

**Comment by sidey79** [comment]
Gute Idee, immer her damit :)

**Comment by HomeAutoUser** [comment]
@sidey79, ich denke ich bin was die Ausgaben angeht fertig :-)
Können wir diese Commits in dev schieben oder möchtest du warten bis wir das Problem mit Ralfs Repeat Schleife behoben haben?

**Comment by sidey79** [comment]
@HomeAutoUser 
Meintest Du das jetzt so oder in dev-r33?

**Comment by HomeAutoUser** [comment]
@sidey79, ja das wäre ein guter Schachzug.
Jeder User der die Dev Version nutzt erhält auch somit diese Änderungen mit.

**Comment by sidey79** [comment]
@HomeAutoUser 

Okay, irgendwie war ich auf dem Trichter, es wäre eine Erweiterung der MU Optimierung. Ist es aber nicht. Von daher hätte man den PR auch so nicht machen müssen.

Ich habe die commits jetzt in dev-r33 überführt und hoffe dabei keinen Fehler gemacht zu haben :)

**Comment by HomeAutoUser** [comment]
@sidey79,
können wir den Branch dev-r33_new_Parse_MU und dev-r33 abgleichen?
Ich habe das Gefühl das bei dem einen einiges drin ist was bei dem anderen nicht ist.

**Pull request merged**
