### PR TITLE
new protocol 27 for EuroChron EFTH-800

### PR DESCRIPTION
**Pull request by elektron-bbs**
* **Please check if the PR fulfills these requirements**

- [x] Tests for the changes have been added / modified (needed for for bug fixes / features)
- [x] commandref has been added / updated (needed for bug fixes / features)
- [x] CHANGED has been updated (needed for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
no decoding of this protocol
https://github.com/RFD-FHEM/RFFHEM/issues/739

* **What is the new behavior (if this is a feature change)?**
decoding of this protocol

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Comment by sidey79** [comment]
Haben wir dafür schon Testdaten im SIGNALduino_Tool json?

**Comment by elektron-bbs** [comment]
Du kannst es wieder mal nicht erwarten, deine Tests zu erstellen :-)
Die Daten sind jetzt im Branch pre-release.

**Comment by sidey79** [comment]
Die Tests müssen nicht erstellt werden, die laufen doch automatisch auf das JSON ab, aber ja :)

**Comment by sidey79** [comment]
Sieht doch gut aus:

```
    ok 52 - [37]: SD_WS_27_TH_2: [0]  { # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        ok 1 - SIGNALduno_Dispatch check id  # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        ok 2 - SIGNALduno_Dispatch check dmsg  # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        1..2
    }
    ok 53 - [38]: SD_WS_27_TH_3: [0]  { # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        ok 1 - SIGNALduno_Dispatch check id  # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        ok 2 - SIGNALduno_Dispatch check dmsg  # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        1..2
    }
    ok 54 - [38]: SD_WS_27_TH_3: [1]  { # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        ok 1 - SIGNALduno_Dispatch check id  # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        ok 2 - SIGNALduno_Dispatch check dmsg  # TODO Checking with prerelease Version of SD_Device_ProtocolList which can fail
        1..2
    }

```

**Pull request merged**
