### PR TITLE
Integrate Unittests from UnitTest Repository into this repository on the fly

### PR DESCRIPTION
**Pull request by sidey79**
* **Please check if the PR fulfills these requirements**

- [ ] Tests for the changes have been added / modified (needed for for bug fixes / features)
- [ ] commandref has been added / updated (needed for bug fixes / features)
- [ ] CHANGED has been updated (needed for bug fixes / features)

* **What kind of change does this PR introduce?** 

**Feature:**
After moving the UnitTest module into a seperate repository, this caused some changes to get it working.

This Project now has a makefile (make test) which is running tests against modules included here.
1. Downloads a makefile from the UnitTest Repostory
2. Copy unittest specific libs and json files into the correct directory under /opt/fhem
3. call make to run tests with options PERL_OPTS="-MDevel::Cover" (uses makefile from the UnitTest Repostory)
    a) This will again copy standard module files to the correct locations under /opt/fhem
    b) Restart fhem with special unittest configuration  
    c) Runs every testfile which is located unter RFFHEM\UnitTest\tests and fulfills naming policy.
    d) stops fhem 

* **What is the current behavior?** (You can also link to an open issue here)

A copy of the unittest module resides static in our repository. Updates must be added manually.
The project makefile runs test only explicit specified testfiles. 

* **What is the new behavior (if this is a feature change)?**

The unittest module (with all needed files) is downloaded from the unittest repository before starting a test.
The project makefile in this project is minimalistic, because it triggers the makefile from the unittest repository which is more complex but independend from the specific tests.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No breaking change known, maybe modified testfiles must be matched to the new location

* **Other information**:

This PR will use the makefile from the UnitTest repository for running tests. So the local makefile is reduced to a few lines.

### CODE REVIEW

**Comment by sidey79** [comment]
ich warte mit dem Merge auf #554 und #550 wegen Anpassungen

**Comment by sidey79** [comment]
@HomeAutoUser 
Sodele, der PR ist nun konfliktfrei

**Comment by HomeAutoUser** [comment]
Wieder da in der OnlineWelt :D
Ich schaue es mir heute Daheim an.

**Comment by sidey79** [comment]
@HomeAutoUser 
hattest Du schon Gelegenheit es mal anzusehen?

**Pull request merged**
